// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args [0]);
		int big = 0;
		int small = 0;
		double num;
		while (N>0){
			num = Math.random();
			if (num>0.5)
				big++;
			else
			small++;
			N = N-1;
		}
		double ratio = (double) big/small;
		System.out.println("> 0.5: " + big + " times");
		System.out.println("<= 0.5: " + small + " times");
		if (big != 0 && small != 0)
		System.out.println("ratio: " + ratio);
	}
}
